export const GET_MENU = 'GET_MENU';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';

export const STUDENT_GET_QUIZ_TEST_LIST = 'STUDENT_GET_QUIZ_TEST_LIST';
export const STUDENT_GET_QUIZ_TEST_LIST_SUCCESS = 'STUDENT_GET_QUIZ_TEST_LIST_SUCCESS';
export const STUDENT_GET_QUIZ_TEST_LIST_FAILURE = 'STUDENT_GET_QUIZ_TEST_LIST_FAILURE';

export const STUDENT_ATTEND_QUIZ_TEST = 'STUDENT_ATTEND_QUIZ_TEST';
export const STUDENT_ATTEND_QUIZ_TEST_SUCCESS = 'STUDENT_ATTEND_QUIZ_TEST_SUCCESS';
export const STUDENT_ATTEND_QUIZ_TEST_FAILURE = 'STUDENT_ATTEND_QUIZ_TEST_FAILURE';

export const STUDENT_GET_QUIZ_TEST_DETAIL = 'STUDENT_GET_QUIZ_TEST_DETAIL';
export const STUDENT_GET_QUIZ_TEST_DETAIL_SUCCESS = 'STUDENT_GET_QUIZ_TEST_DETAIL_SUCCESS';
export const STUDENT_GET_QUIZ_TEST_DETAIL_FAILURE = 'STUDENT_GET_QUIZ_TEST_DETAIL_FAILURE';

export const STUDENT_GET_CLASS_LIST = 'STUDENT_GET_CLASS_LIST';
export const STUDENT_GET_CLASS_LIST_SUCCESS = 'STUDENT_GET_CLASS_LIST_SUCCESS';
export const STUDENT_GET_CLASS_LIST_FAILURE = 'STUDENT_GET_CLASS_LIST_FAILURE';

export const STUDENT_GET_CLASS_INFORMATION = 'STUDENT_GET_CLASS_INFORMATION';
export const STUDENT_GET_CLASS_INFORMATION_SUCCESS = 'STUDENT_GET_CLASS_INFORMATION_SUCCESS';
export const STUDENT_GET_CLASS_INFORMATION_FAILURE = 'STUDENT_GET_CLASS_INFORMATION_FAILURE';

export const STUDENT_GET_CLASS_SESSION_LIST = 'STUDENT_GET_CLASS_SESSION_LIST';
export const STUDENT_GET_CLASS_SESSION_LIST_SUCCESS = 'STUDENT_GET_CLASS_SESSION_LIST_SUCCESS';
export const STUDENT_GET_CLASS_SESSION_LIST_FAILURE = 'STUDENT_GET_CLASS_SESSION_LIST_FAILURE';

export const STUDENT_GET_ACTIVE_QUIZ_OF_SESSION = 'STUDENT_GET_ACTIVE_QUIZ_OF_SESSION';
export const STUDENT_GET_ACTIVE_QUIZ_OF_SESSION_SUCCESS = 'STUDENT_GET_ACTIVE_QUIZ_OF_SESSION_SUCCESS';
export const STUDENT_GET_ACTIVE_QUIZ_OF_SESSION_FAILURE = 'STUDENT_GET_ACTIVE_QUIZ_OF_SESSION_FAILURE';

export const STUDENT_GET_CLASS_MEMBER_LIST = 'STUDENT_GET_STUDENT_CLASS_MEMBER_LIST';
export const STUDENT_GET_CLASS_MEMBER_LIST_SUCCESS = 'STUDENT_GET_STUDENT_CLASS_MEMBER_LIST_SUCCESS';
export const STUDENT_GET_CLASS_MEMBER_LIST_FAILURE = 'STUDENT_GET_STUDENT_CLASS_MEMBER_LIST_FAILURE';

export const STUDENT_GET_CLASS_ASSIGNMENT_LIST = 'STUDENT_GET_CLASS_ASSIGNMENT_LIST';
export const STUDENT_GET_CLASS_ASSIGNMENT_LIST_SUCCESS = 'STUDENT_GET_CLASS_ASSIGNMENT_LIST_SUCCESS';
export const STUDENT_GET_CLASS_ASSIGNMENT_LIST_FAILURE = 'STUDENT_GET_CLASS_ASSIGNMENT_LIST_FAILURE';

export const STUDENT_GET_CLASS_CHAPTER_LIST = 'STUDENT_GET_CLASS_CHAPTER_LIST';
export const STUDENT_GET_CLASS_CHAPTER_LIST_SUCCESS = 'STUDENT_GET_CLASS_CHAPTER_LIST_SUCCESS';
export const STUDENT_GET_CLASS_CHAPTER_LIST_FAILURE = 'STUDENT_GET_CLASS_CHAPTER_LIST_FAILURE';

export const STUDENT_GET_CLASS_QUIZ_LIST = 'STUDENT_GET_CLASS_QUIZ_LIST';
export const STUDENT_GET_CLASS_QUIZ_LIST_SUCCESS = 'STUDENT_GET_CLASS_QUIZ_LIST_SUCCESS';
export const STUDENT_GET_CLASS_QUIZ_LIST_FAILURE = 'STUDENT_GET_CLASS_QUIZ_LIST_FAILURE';

export const STUDENT_POST_ACTIVE_QUIZ_OF_SESSION = 'STUDENT_POST_ACTIVE_QUIZ_OF_SESSION';
export const STUDENT_POST_ACTIVE_QUIZ_OF_SESSION_SUCCESS = 'STUDENT_POST_ACTIVE_QUIZ_OF_SESSION_SUCCESS';
export const STUDENT_POST_ACTIVE_QUIZ_OF_SESSION_FAILURE = 'STUDENT_POST_ACTIVE_QUIZ_OF_SESSION_FAILURE';

export const STUDENT_GET_REGISTER_CLASS_LIST = 'STUDENT_GET_REGISTER_CLASS_LIST';
export const STUDENT_GET_REGISTER_CLASS_LIST_SUCCESS = 'STUDENT_GET_REGISTER_CLASS_LIST_SUCCESS';
export const STUDENT_GET_REGISTER_CLASS_LIST_FAILURE = 'STUDENT_GET_REGISTER_CLASS_LIST_FAILURE';

export const STUDENT_ATTEND_CLASS = 'STUDENT_ATTEND_CLASS';
export const STUDENT_ATTEND_CLASS_SUCCESS = 'STUDENT_ATTEND_CLASS_SUCCESS';
export const STUDENT_ATTEND_CLASS_FAILURE = 'STUDENT_ATTEND_CLASS_FAILURE';
