export const GET_MENU = 'GET_MENU';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';

export const GET_QUIZ_TEST_LIST = 'GET_QUIZ_TEST_LIST';
export const GET_QUIZ_TEST_LIST_SUCCESS = 'GET_QUIZ_TEST_LIST_SUCCESS';
export const GET_QUIZ_TEST_LIST_FAILURE = 'GET_QUIZ_TEST_LIST_FAILURE';

export const ATTEND_QUIZ_TEST = 'ATTEND_QUIZ_TEST';
export const ATTEND_QUIZ_TEST_SUCCESS = 'ATTEND_QUIZ_TEST_SUCCESS';
export const ATTEND_QUIZ_TEST_FAILURE = 'ATTEND_QUIZ_TEST_FAILURE';

export const GET_QUIZ_TEST_DETAIL = 'GET_QUIZ_TEST_DETAIL';
export const GET_QUIZ_TEST_DETAIL_SUCCESS = 'GET_QUIZ_TEST_DETAIL_SUCCESS';
export const GET_QUIZ_TEST_DETAIL_FAILURE = 'GET_QUIZ_TEST_DETAIL_FAILURE';

export const GET_STUDENT_CLASS_LIST = 'GET_STUDENT_CLASS_LIST';
export const GET_STUDENT_CLASS_LIST_SUCCESS = 'GET_STUDENT_CLASS_LIST_SUCCESS';
export const GET_STUDENT_CLASS_LIST_FAILURE = 'GET_STUDENT_CLASS_LIST_FAILURE';

export const GET_STUDENT_CLASS_INFORMATION = 'GET_STUDENT_CLASS_INFORMATION';
export const GET_STUDENT_CLASS_INFORMATION_SUCCESS = 'GET_STUDENT_CLASS_INFORMATION_SUCCESS';
export const GET_STUDENT_CLASS_INFORMATION_FAILURE = 'GET_STUDENT_CLASS_INFORMATION_FAILURE';

export const GET_STUDENT_CLASS_SESSIONS = 'GET_STUDENT_CLASS_SESSIONS';
export const GET_STUDENT_CLASS_SESSIONS_SUCCESS = 'GET_STUDENT_CLASS_SESSIONS_SUCCESS';
export const GET_STUDENT_CLASS_SESSIONS_FAILURE = 'GET_STUDENT_CLASS_SESSIONS_FAILURE';

export const GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT = 'GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT';
export const GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_SUCCESS = 'GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_SUCCESS';
export const GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_FAILURE = 'GET_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_FAILURE';

export const GET_STUDENT_CLASS_MEMBERS = 'GET_STUDENT_CLASS_MEMBERS';
export const GET_STUDENT_CLASS_MEMBERS_SUCCESS = 'GET_STUDENT_CLASS_MEMBERS_SUCCESS';
export const GET_STUDENT_CLASS_MEMBERS_FAILURE = 'GET_STUDENT_CLASS_MEMBERS_FAILURE';

export const GET_STUDENT_CLASS_ASSIGNMENTS = 'GET_STUDENT_CLASS_ASSIGNMENTS';
export const GET_STUDENT_CLASS_ASSIGNMENTS_SUCCESS = 'GET_STUDENT_CLASS_ASSIGNMENTS_SUCCESS';
export const GET_STUDENT_CLASS_ASSIGNMENTS_FAILURE = 'GET_STUDENT_CLASS_ASSIGNMENTS_FAILURE';

export const GET_STUDENT_CLASS_CHAPTERS = 'GET_STUDENT_CLASS_CHAPTERS';
export const GET_STUDENT_CLASS_CHAPTERS_SUCCESS = 'GET_STUDENT_CLASS_CHAPTERS_SUCCESS';
export const GET_STUDENT_CLASS_CHAPTERS_FAILURE = 'GET_STUDENT_CLASS_CHAPTERS_FAILURE';

export const GET_STUDENT_CLASS_QUIZZES = 'GET_STUDENT_CLASS_QUIZZES';
export const GET_STUDENT_CLASS_QUIZZES_SUCCESS = 'GET_STUDENT_CLASS_QUIZZES_SUCCESS';
export const GET_STUDENT_CLASS_QUIZZES_FAILURE = 'GET_STUDENT_CLASS_QUIZZES_FAILURE';

export const POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT = 'POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT';
export const POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_SUCCESS = 'POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_SUCCESS';
export const POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_FAILURE = 'POST_ACTIVE_QUIZ_OF_SESSION_FOR_STUDENT_FAILURE';