name: Basewebfrontend Image CI

on:
  push:
    branches:
      - master
    paths:
      - "frontend/webreactjs/basewebfrontend/**"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code
      #     - name: Build the Docker image
      #       run: docker build . --file Dockerfile --tag basewebfrontend:$(date +%s)
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/basewebfrontend
          #         tags: v1, latest
          directory: "frontend/webreactjs/basewebfrontend/"
          registry: docker.io
          dockerfile: "frontend/webreactjs/basewebfrontend/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
#        addTimestamp: true
