name: Baseweb Image CI

on:
  push:
    branches:
      - master
    paths:
      - "backend/springboot/baseweb/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Create file appication.yml
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'application.yml'
          fileDir: './backend/springboot/baseweb/src/main/resources/'
          encodedString: ${{ secrets.B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/baseweb
          directory: "backend/springboot/baseweb/"
          registry: docker.io
          dockerfile: "backend/springboot/baseweb/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: './backend/springboot/baseweb/src/main/resources/application.yml'
