name: Peer Server Image CI

on:
  push:
    branches:
      - master
    paths:
      - "backend/nodejs/peer-server/**"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      #     - name: Build the Docker image
      #       run: docker build . --file Dockerfile --tag socket-server:$(date +%s)
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/peer-server
          #         tags: v1, latest
          directory: "backend/nodejs/peer-server/"
          registry: docker.io
          dockerfile: "backend/nodejs/peer-server/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
#        addTimestamp: true